pr: none
trigger: none

schedules:
- cron: '0 0 * * *'
  always: true
  branches:
    include:
    - main

jobs:
- job: cleanup
  pool: sonic-ubuntu-1c
  timeoutInMinutes: 240

  steps:
    - checkout: none
    - script: |
        # Wait for apt lock to be released (timeout after 10 minutes)
        timeout=600
        elapsed=0
        while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || sudo fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || sudo fuser /var/cache/apt/archives/lock >/dev/null 2>&1; do
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for apt lock after 10 minutes"
            exit 1
          fi
          echo "Waiting for apt lock to be released..."
          sleep 5
          elapsed=$((elapsed + 5))
        done

        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      displayName: install dependencies
    - task: AzureCLI@2
      displayName: clean ACR
      inputs:
        azureSubscription: 'WIF-soniccr1'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account show
          for registry in $(sonic_acrs); do
            az acr run --registry $registry --cmd "acr purge --filter '.*:.*'  --ago 1200d " --timeout 3600 /dev/null || true
            az acr run --registry $registry --cmd "acr purge --filter '.*:.*bld.*' --ago 365d" --timeout 3600 /dev/null || true
            az acr run --registry $registry --cmd "acr purge --filter '.*:.*' --untagged --ago 360d" --timeout 3600 /dev/null || true
          done
